---
- hosts: all
  tasks:
    - name: install httpd
      package: name=httpd state=latest
    - name: install httpd
      package:
         name: httpd
         state: latest
      become: yes
    - name: index.html
      copy:
         content: "this is a webpage"
         dest: /var/www/html/index.html
      become: yes
    - name: restart httpd
      service:
          name: httpd
          state: restarted
          enabled: yes
      become: yes
          
